### ISSUE TITLE
questions about metrics 

### ISSUE THREAD

**Issue by Arlo0321** [thaoshibe/visii#9]
Hi author, thanks for your team's contribution.

I would like to ask you a question about calculating the metrics during the training process. Specifically, the training process is usually interspersed with a validation step, do you perform the computation of the evaluation metrics during the validation step, which seems to be time consuming. So I'm wondering how you schedule the evaluation during the training process?

**Comment by thaoshibe** [comment]
Hi houjie8888,

I didnt calculating the metrics during the training process (e.g., validation step). Rather than that, I just simply train for 1000 timesteps and save the best checkpoints (checkpoint with lowest MSE loss) (check the code [here](https://github.com/thaoshibe/visii/blob/83e678fd6e1d8db16a8a507fcf94e7986627f28d/visii.py#L949)).

Please check *[4.1 Experimental Settings](https://openreview.net/pdf?id=l9BsCh8ikK)* in our main paper for more details.
Thank you!
